blank_issues_enabled: false
contact_links:
  - name: Ask a question on Discussions
    url: https://github.com/gerwin/mkb-stack/discussions/new?category=q-a
    about: Ask questions and get answers from the community.
