name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          path: "ansible/"

  mdl:
    name: Markdown Lint (mdl)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby
        run: sudo apt-get update && sudo apt-get install -y ruby
      - name: Install mdl
        run: sudo gem install mdl
      - name: Run mdl
        run: mdl --style all --warnings --config .mdlrc -g -- ./docs/* *.md ./.github/* 